### ISSUE TITLE
修改外部链接逻辑

### ISSUE THREAD

**Issue by Donaar-dev** [SUSTech-CRA/sustech-online-wxapp#5]
修改外部链接逻辑

https://github.com/docker-practice/miniprogram/blob/8d9a0097fc070ea6b95aa7dfbeb28d9bd8cea1fc/client/src/utils/OpenGithub.ts

**Comment by Donaar-dev** [comment]
https://blog.csdn.net/qq_34507902/article/details/79091758

**Comment by liziwl** [comment]
不采用上面的方式，用页面的方式实现了。https://github.com/SUSTC/sustech-online-wxapp/commit/f734637dc8430eded1f9393a8116c8aff4bad75f

**Comment by liziwl** [comment]
https://developers.weixin.qq.com/community/develop/doc/00024c7b6640b0059da96c61c54c00 , 需要修复打开pdf 链接的逻辑，现在是会显示about页面

**Comment by liziwl** [comment]
https://www.hlwen.com/2020/10/30/55.html

```js
a = new URL("https://mirrors.sustech.edu.cn/site/sustech-online/documents/campus-map/%E5%8D%97%E6%96%B9%E7%A7%91%E6%8A%80%E5%A4%A7%E5%AD%A6%E6%A0%A1%E5%9B%AD%E5%9C%B0%E5%9B%BE-v3-1.pdf?sdcasdc=12122")
a.pathname.split('.').pop().toUpperCase()
```

**Comment by liziwl** [comment]
跳转页面样式又乱了

**Comment by liziwl** [comment]
https://github.com/SUSTC/sustech-online-wxapp/commit/28b5b425700038be921d515ee1c10ecf20208c14

修复完成
