### ISSUE TITLE
微信小程序加载文件加个进度条，或者百分数

### ISSUE THREAD

**Issue by Donaar-dev** [SUSTech-CRA/sustech-online-wxapp#6]
example：

- https://www.wxapp-union.com/article-4759-1.html

- https://juejin.cn/post/6844903741636755463

**Comment by Donaar-dev** [comment]
显示下载文件大小

**Comment by liziwl** [comment]
update at https://github.com/SUSTC/sustech-online-wxapp/commit/a83930899315bcc1bd3f95bfb94791cf3dbd4222
